[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "kanslokartan"
version = "0.1.5"
description = "Emotion recognition and journal for autism and ADHD"
license = "GPL-3.0-or-later"

[tool.setuptools.packages.find]
where = ["."]
